### ISSUE TITLE
coredns + external-dns chart

### ISSUE THREAD

**Issue by bl-ue** [coredns/helm#1]
Could we add a chart for an [external-dns](https://github.com/kubernetes-sigs/external-dns) setup with CoreDNS and etcd?

I would be happy to open a PR.  I'm working a chart like this right now.

/cc @chrisohaver

**Comment by chrisohaver** [comment]
That kind of feels like it should fall into the external-dns domain.

**Comment by haad** [comment]
Can you better describe what you want ? external-dns chart can be found here https://artifacthub.io/packages/helm/bitnami/external-dns

**Comment by bl-ue** [comment]
@chrisohaver I agree with you, but I couldn't find any official external-dns charts location.

@haad I somehow never noticed that.  I'll try it out.  It looks promising, seeing that it has configuration parameters for all supported providers. I don't see a `coredns.etcdPrefix`, but maybe I'll open and issue on bitnami's repo.  Thank you for that link!

**Comment by bl-ue** [comment]
Sorry @chrisohaver I forgot to reply back!  I think the external-dns chart is what I want.  Thank you and @haad for the help!
