### ISSUE TITLE
$ symbol escape

### ISSUE THREAD

**Issue by flylan** [coredns/helm#119]
ZoneFiles requires the addition of the $symbol, but I have tried many methods but cannot add the $symbol to the configmap

I have tried the following methods：
```go
1.Change $ to \$
2.Change $ to \\$
3.Change $ to {{`$`}}
4.Change $ to {{ print "$" }}
``` 

None of the above methods are available

![image](https://user-images.githubusercontent.com/12097229/233530685-8c22e4ad-40e2-40ff-9c3c-28cb471583d3.png)

**Comment by flylan** [comment]
It seems that helm treated $ORIGIN and $TTL as variables

![image](https://user-images.githubusercontent.com/12097229/233531618-512dbae1-68b3-433d-bcd8-1ada14002118.png)

**Comment by flylan** [comment]
That's not good either：

![image](https://user-images.githubusercontent.com/12097229/233532307-6eff2cb8-589e-4caf-84d6-baefe8f26e4c.png)
![image](https://user-images.githubusercontent.com/12097229/233532700-87785952-7579-420e-80f8-5f1f59b5489a.png)

**Comment by flylan** [comment]
> What helm version are you using?

3.8.1

**Comment by hagaibarel** [comment]
I run your example through `helm template .` and got the expected results:

```
example.db:     |
      $ORIGIN example.com.
      $TTL 86400
    
      @ 3600 IN SOA example.com. rname.invalid. 2023041914 3600 60 1209600 3600
    
      abc IN A 192.168.33.11
      *   IN A 192.168.33.10
```

I'm using helm v3.11.1. Would you mind upgrading your helm installation and try again please? Either way this seems like a helm issue, not so much with this chart

**Comment by flylan** [comment]
> 



> I run your example through `helm template .` and got the expected results:
> 
> ```
> example.db:     |
>       $ORIGIN example.com.
>       $TTL 86400
>     
>       @ 3600 IN SOA example.com. rname.invalid. 2023041914 3600 60 1209600 3600
>     
>       abc IN A 192.168.33.11
>       *   IN A 192.168.33.10
> ```
> 
> I'm using helm v3.11.1. Would you mind upgrading your helm installation and try again please? Either way this seems like a helm issue, not so much with this chart

I upgraded helm to 3.11.1, but the problem still persists
![image](https://user-images.githubusercontent.com/12097229/233917709-21f2c440-a973-4b90-ba22-73a3d751eeb4.png)

```go
zoneFiles:
  - filename: example.com.db
    domain: example.com
    contents: |-
      $ORIGIN example.com.
      $TTL 86400
      
      @ 3600 IN SOA example.com. rname.invalid. 2023041914 3600 60 1209600 3600
      
      abc IN A 192.168.33.11
      *   IN A 192.168.33.10
``` 

I used PHP Storm as the editor, turned on the display space function, and confirmed that there were no tabs in the configuration

![image](https://user-images.githubusercontent.com/12097229/233917024-0995627d-7efc-4a69-8a7d-7fd5de95fce5.png)

When I execute the help template --debug . , this configuration will report an error

![image](https://user-images.githubusercontent.com/12097229/233917153-35aa2e5a-5432-424c-9817-30b21998dd39.png)

After I removed this configuration
![image](https://user-images.githubusercontent.com/12097229/233918734-607a19be-fac4-47e6-a433-b6b11f034996.png)

or add escape symbol:
![image](https://user-images.githubusercontent.com/12097229/233918908-bfe55073-285d-42db-9310-526e0721eef6.png)


helm template --debug . can run, but $XXX will be treated as a variable and not output
![image](https://user-images.githubusercontent.com/12097229/233917475-b80124d7-389c-4cf9-82b8-ab3ebd58f612.png)
![image](https://user-images.githubusercontent.com/12097229/233919167-5d0251c3-b493-4817-94d9-a327968d2574.png)

It seems that helm has been treating $XXX as a variable

**Comment by flylan** [comment]
> I can't reproduce it, in the rendered chart I get the `$` properly in the right place. As this isn't an issue with the `coredns` chart, I recommend you raise an issue in https://github.com/helm/helm/issues, they might be able to help you better

okay, thank you
