### ISSUE TITLE
Latest Chart version release not in sync with the actual github release

### ISSUE THREAD

**Issue by ebrianne** [coredns/helm#16]
The latest Chart release number is 1.14.3 however, the latest release packed on github is 1.14.1. This breaks the coredns helm deployment at the moment as the patch for the cluster role is not present.

**Comment by viceice** [comment]
Looks like there is something wrong with automatic releases
![image](https://user-images.githubusercontent.com/1798109/111260360-f0164980-8620-11eb-9c67-fe49782526e6.png)
