### ISSUE TITLE
We have already supported hot updates, can this modification be deleted?

### ISSUE THREAD

**Issue by hcwnbs** [coredns/helm#161]
reload:
![image](https://github.com/coredns/helm/assets/28859665/161acccb-2cda-4bc5-9fbf-9693eca95891)

checksum
![image](https://github.com/coredns/helm/assets/28859665/9bf8348f-e4e0-4d04-9caf-33c956cd3376)

**Comment by hagaibarel** [comment]
That's a good idea, my only concern is that when people use a custom configuration without the `reload` plugin we won't get the automatic pod restart when the config changes

**Comment by hcwnbs** [comment]
> That's a good idea, my only concern is that when people use a custom configuration without the `reload` plugin we won't get the automatic pod restart when the config changes

Got it
