### ISSUE TITLE
help with PR 50

### ISSUE THREAD

**Issue by craig5** [coredns/helm#51]
Creating an "issue" feels a bit "heavy handed", but I am not sure what else to try.

I create a PR to add scrape interval to the service monitor:
https://github.com/coredns/helm/pull/50

But, I can't "signoff" and it doesn't look like I can add reviewers/assignees/...

I don't see any kind of "contributing.md" doc for guidance. So, I am a little stuck...

**Comment by chrisohaver** [comment]
Asking in the PR [like you have already done](https://github.com/coredns/helm/pull/50#issuecomment-1021457735) works.  No need for a separate issue.
