### ISSUE TITLE
Invalid yaml produced for service-metrics

### ISSUE THREAD

**Issue by Diaoul** [coredns/helm#60]
It seems that the yaml generated for service metric is invalid due to [this](https://github.com/coredns/helm/commit/599dcca744412e85adf1ca6b97e23a411301d683#diff-5b1511e2c64aa669dea241871703a0a8b601b2d348d4af6d19049c6cf366c52f) change.
I am no helm templating expert but there probably is an empty newline or something like this.

For context, the error was spotted by flux on v1.18.0 up to v1.19.0 with a failed JSON conversion:
```
Helm upgrade failed: YAML parse error on coredns/templates/service-metrics.yaml: error converting YAML to JSON: yaml: line 13: did not find expected key
```

**Comment by ebarped** [comment]
Hi:
It seems that when prometheus.service.enabled is set to true, you MUST define at least 1 service.annotations.
Try to define something like:
```yaml
service:
  name: "kube-dns"
  annotations:
    test: test
```

**Comment by Diaoul** [comment]
I confirm this is working. Can this limitation be lifted?

**Comment by mrueg** [comment]
@Mattes83 it looks like this change was introduced with https://github.com/coredns/helm/pull/53 can you take a look?
