### ISSUE TITLE
`replicas` in the helm chart should be omitted when hpa is enabled

### ISSUE THREAD

**Issue by b2jrock** [coredns/helm#64]
https://github.com/coredns/helm/blob/master/charts/coredns/templates/deployment.yaml#L31

Currently replicas are not set when the cluster-proportional autoscaler is enabled. This case should be extended to include when `hpa.enabled` is true. 

It seems this may have worked on helm2, but the behavior changed for helm3:
https://github.com/helm/helm/issues/7090

**Comment by hagaibarel** [comment]
Fixed in https://github.com/coredns/helm/pull/116
