### ISSUE TITLE
Warning - beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead

### ISSUE THREAD

**Issue by orsenthil** [coredns/helm#83]
When I tried to edit a coredns deployment (coredns version 1.9.1) I got these warning messages.

```
kubectl edit deployment coredns -n kube-system
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead
 deployment.apps/coredns edited
```

What should I do? Is this specific to any helm chart that I was using? Any guidance?

**Comment by Aminechakr** [comment]
Same bug with a warning message

**Comment by msa21** [comment]
I am also getting the same warning while updating coredns in eks cluster.

**Comment by aakilin** [comment]
I've faced the same warning. Any updates?

**Comment by matiassalinas** [comment]
I got the same warning message while [updating self-managed add-on](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html) from v1.8.4-eksbuild.1 to v1.8.7-eksbuild.4

The procedure i followed will be replaced on July 1, 2023 with the EKS add-on. I hope this warning would be removed if we migrate our add-on. Someone using EKS add-on who can tell us if the warning message disappears?

**Comment by HagaiBarel** [comment]
Did you get the error message while trying to update the `coredns` deployment installed using this chart?

**Comment by hagaibarel** [comment]
Going to close this as stale, feel free to raise another issue if needed

**Comment by brsolomon-deloitte** [comment]
```shell
$ kubectl set image deployment.apps/coredns -n kube-system \
>     coredns=<redacted>.dkr.ecr.<redacted>.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead
deployment.apps/coredns image updated
```

@hagaibarel this is not stale; it occurs when upgrading to the most recent version of CoreDNS - please re-open it.

**Comment by hagaibarel** [comment]
@brsolomon-deloitte please provide the following so we can try to understand why this happens:
* Chart version used to install coredns
* Chart values used (leave out sensitive values if any)
* Kubernetes distro (EKS, GKE, AKS etc.) and version

**Comment by brsolomon-deloitte** [comment]
> @brsolomon-deloitte please provide the following so we can try to understand why this happens:

Installing directly from the `v1.9.3-eksbuild.2` YAML manifests on Amazon EKS 1.25. No custom values used.

**Comment by hagaibarel** [comment]
> Installing directly from the `v1.9.3-eksbuild.2` YAML manifests on Amazon EKS 1.25. No custom values used.

So this isn't related to this chart and out of scope. I suggest you continue investigating this with whoever manages those `yaml` files

**Comment by michaelm-88** [comment]
@hagaibarel why this closed ??

i try today to upgrade and stii can see it 

```
 kubectl set image deployment.apps/coredns -n kube-system  coredns=602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/coredns:v1.11.1-eksbuild.6
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead
deployment.apps/coredns image updated
```

**Comment by hagaibarel** [comment]
@michaelm-88 this is closed because the issue wasn't about the chart, it was about coredns manifests managed elsewhere (see https://github.com/coredns/helm/issues/83#issuecomment-1501663831)

If you have problems while using the chart, pleae open a different issue
