### ISSUE TITLE
Service is getting created with special chars in argo

### ISSUE THREAD

**Issue by kalpanathanneeru21** [coredns/helm#92]
While trying to upgrade coredns chart 1.16.3 to 1.16.7, core-dns 1.8.4 to 1.8.7 observed the issue.
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/85505383/216351300-0725413f-aaf5-45b1-bdeb-35869bcf15e3.png">

Tried from 1.16.5 to 1.18.0 charts having the same issue.

I need help to upgrade cordens to 1.8.7.

**Comment by HagaiBarel** [comment]
Can you please provide the argo application configuration you're using?

**Comment by kalpanathanneeru21** [comment]
> Can you please provide the argo application configuration you're using?

issue got solved somehow. Thanks
