### ISSUE TITLE
Looking for new chart maintainers

### ISSUE THREAD

**Issue by mrueg** [coredns/helm#96]
Hi,

this project is looking for new maintainers to support the helm charts for CoreDNS!

If you are interested, please reach out here.

CC: @chrisohaver

**Comment by hungran** [comment]
me too, happy to support, please mess me or DM via cncf slack org

**Comment by daotoan-hd** [comment]
Hi, I'd love to take part of the gang!

**Comment by shubham-cmyk** [comment]
@mrueg 
Are you interested in taking me as a part of helm chart maintainer of the `Core DNS`

**Comment by mrueg** [comment]
@hungran @daotoan-hd @shubham-cmyk please reach out to @hagaibarel and myself on kubernetes slack.

**Comment by shubham-cmyk** [comment]
@mrueg @hagaibarel 
I have pinged you guys over Slack please check

**Comment by shubham-cmyk** [comment]
This could be closed now 
@mrueg @hagaibarel
